server:
    port: 0
spring:
    application:
        name: ms-reports-listener
    profiles:
        default: default
    data:
        mongodb:
            authentication-database: admin
            host: localhost
            port: 27017
            username: sa
            password: sa

    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
            function:
                bindings:
                    consumerReport-in-0:
                        destination: consumerReport

eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone:  http://localhost:8761/eureka/
