server:
    port: 4040
spring:
    application:
        name: ms-gateway
    profiles:
        default: eureka-on
eureka:
    fetch-registry: true
    client:
        service-url:
            defaultZone:  http://localhost:8761/eureka/

